name: TestMap
variant: test
sniper:
  spawn:
    x: 2.5
    y: -54
    z: 1.5
  config:
    weapon: true
    spyglass: true
    cctv-access: false
spawnpoints:
  s1:
    x: 0
    y: 4
    z: 0
    radius: 5
cameras:
  camera-1:
    name: "1"
    location:
      x: 0
      y: 0
      z: 0
    yaw: 90
    pitch: -45
quests:
  q1:
    type: interaction
    name: "atm pay"
    validation: shared
    interaction:
      target:
        block: "iron_block"
        x: 5
        y: 4
        z: 0
      key:
        item: "gold_ingot"
        custom_id: "credit_card"
